# ----------------------------------------------------------------------------------------------------------------------
[global]
    seed = 3                                                      # seed value to yield reproducable results
    date_format = "%Y-%m-%d"                                        # date format used globally
    num_age_groups_pop = 4                                          # number of population age groups
    num_age_groups_hh = 4                                           # number of household age groups

# ----------------------------------------------------------------------------------------------------------------------
[simulation]
start_date = "2011-1-1"                                             # start date simulation
end_date = "2011-12-31"                                             # end date simulation

initial_influx = 3                                                                                   # initial influx
influx_period_in_days = 2                                           # influx every x days
num_influx_per_period = 0                                           # daily influx

terminate_on_zero_infected = true                                   # terminate if num. infected reaches zero

    # ------------------------------------------------------------------------------------------------------------------
    [simulation.reporter]
    enabled = true                                                  # whether to report while running
    report_period_in_days = 2                                       # report every x days
    line_length = 100                                               # line length for formatting

    sink = "console"                                                # sink for writing reporter data
    log_level = ["error", "info"]                                   # types of logs to show, i.e., debug, info, error

        [simulation.reporter.sinks]                                 # sink specific settigs

            # File sink
            [simulation.reporter.sinks.file]                        # file sink specific settings
            output_file_name = "./output/reporter_output.txt"       # name of the output file in-case file sink is used
    # ------------------------------------------------------------------------------------------------------------------
    [simulation.disease]

        [simulation.disease.logger]
            enabled = true                                          # enable log creation of infection
            tans_log_file_name = "./output/transmission_log.csv"    # file to write transmission log to
            sim_log_file_name = "./output/simulation_log.csv"       # file to write simulation log to
            disease_log_file_name = "./output/disease_log.csv"      # file to write disease log to, i.e., changes in the disease state

        [simulation.disease.transmission]
        pop_matrix = "./input/pop_contact.csv"                      # location population contact matrix
        hh_matrix = "./input/hh_contact_no_children.csv"            # location household contact matrix
        hh_matrix_children = "./input/hh_contact_children.csv"      # location household with children contact matrix
        pop_state_infected = 0.006
        pop_state_symptomatic =  0.012
        pop_state_asymptomatic = 0.006
        household_state_infected  = 0.1#0.2
        household_state_symptomatic = 0.2#0.4
        household_state_asymptomatic = 0.1#0.2

        # beta_household = 0.05                                     # beta household (Deprecated, currently specified in the transmission model)
        # beta_population = 0.95                                    # beta population (Deprecated, currently specified in the transmission model)
    # ------------------------------------------------------------------------------------------------------------------
    [simulation.population]
        age_child_limit = 13                                        # maximum age till individual is considered to be a child (exclusive!)

    # ------------------------------------------------------------------------------------------------------------------
    [simulation.log_player]
    base_population = [1602267, 768437, 6157204, 2410827]                   # Base population is used to compute base age distribution (used to compute adjustment in disease model). From age-distribtution used to compute contact rates per capita
    initial_population = "./input/pop_large_sample_10032020.csv"  #              # location initial population csv
    event_log = "./input/event_log_large_sample_10032020.csv" #"./input/event_log_sample_NH.csv"  #                # location demographic events log
# ----------------------------------------------------------------------------------------------------------------------