# ----------------------------------------------------------------------------------------------------------------------
[simulation]
start_date = "2002-1-1"                                     # start date simulation
end_date = "2002-1-2"                                       # end date simulation

infection_duration = 4                                      # number of days that the disease lasts
initial_influx = 200                                        # initial influx
daily_influx = 20                                           # daily influx

    # ------------------------------------------------------------------------------------------------------------------
    [simulation.reporter]
    enabled = true                                          # whether to report while running
    line_length = 80                                        # line length for formatting
    sink = "console"                                        # sink for writing reporter data (i.e., console or file)
    log_level = "info"                                      # debug, info, error.

        [simulation.reporter.sinks]                         # sink specific settigs

            # File sink
            [simulation.reporter.sinks.file]                # file sink specific settings
            file_name = "output.txt"                        # name of the output file in-case file sink is used
    # ------------------------------------------------------------------------------------------------------------------
    [simulation.transmission]
    pop_matrix = "./data/pop_contact.csv"                   # location population contact matrix
    hh_matrix = "./data/hh_contact_no_children.csv"         # location household contact matrix
    hh_matrix_children = "./data/hh_contact_children.csv"   # location household with children contact matrix

    beta_household = 0.05                                   # beta household

    num_age_groups_pop = 4                                  # population age groups
    num_age_groups_household = 4                            # household age groups
    # ------------------------------------------------------------------------------------------------------------------
    [simulation.population]
    date_format = "%Y-%m-%d"                                # date format used in population and events log
    initial_population = "./data/population.csv"            # location initial population csv
    event_log = "./data/event_log_corrected.csv"            # location demographic events log

        [simulation.population.connector]                   # SQL connector settings
        host = "localhost"
        user = "root"
        password = "root"
        database = "diseases"
# ----------------------------------------------------------------------------------------------------------------------
