[global]
seed = 50
date_format = "%Y-%m-%d"
disease_states = [ "Susceptible", "Infected", "Recovered",]
num_age_groups_pop = 4
num_age_groups_hh = 4

[simulation]
start_date = "2002-1-1"
end_date = "2002-1-2"
initial_influx = 100
influx_period_in_days = 2
num_influx_per_period = 0
terminate_on_zero_infected = true

[simulation.reporter]
enabled = true
report_period_in_days = 2
line_length = 80
sink = "file"
log_level = [ "error", "info",]

[simulation.disease]
infection_duration = 4
age_child_limit = 18

[simulation.log_player]
initial_population = "./input/pop.csv"
event_log = "./input/event_log.csv"

[simulation.disease.logger]
enabled = true
inf_log_file_name = "./output/seed-50/infection_log_seed-50.csv"
sim_log_file_name = "./output/seed-50/simulation_log_seed-50.csv"

[simulation.disease.transmission]
pop_matrix = "./input/pop_contact.csv"
hh_matrix = "./input/hh_contact_no_children.csv"
hh_matrix_children = "./input/hh_contact_children.csv"
beta_household = 0.05
beta_population = 0.6

[simulation.reporter.sinks.file]
output_file_name = "./output/seed-50/reporter_output_seed-50.txt"
